const walletActionTypes = {
  ADD_USER: 'ADD_USER',
  ADD_EXPENSE: 'ADD_EXPENSE',
  EDIT_EXPENSE: 'EDIT_EXPENSE',
  CONFIRM_EDIT_EXPENSE: 'CONFIRM_EDIT_EXPENSE',
  RESET_EDITOR: 'RESET_EDITOR',
  REMOVE_EXPENSE: 'REMOVE_EXPENSE',
  SHOW_TOTAL_EXPENSE: 'SHOW_TOTAL_EXPENSE',
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  SUCCESS_RETURN_CURRENCIES: 'SUCCESS_RETURN_CURRENCIES',
  ERROR_RETURN_CURRENCIES: 'ERROR_RETURN_CURRENCIES',
  FETCH_EXCHANGE_RATES: 'FETCH_EXCHANGE_RATES',
  SUCCESS_RETURN_EXCHANGE_RATES: 'SUCCESS_RETURN_EXCHANGE_RATES',
  ERROR_RETURN_EXCHANGE_RATES: 'ERROR_RETURN_EXCHANGE_RATES',
} as const;

export default walletActionTypes;


